version: '3.1'

services:
    flask:
        container_name: innovationai_flask
        hostname: innovationai_flask
        build: 
            context: ./flask/
            dockerfile: Dockerfile
        image: innovationai_flask:1.1
        ports:
            - "8000:8000"
        volumes:
            - ./flask:/home/app/
        depends_on:
            - database
    database:
        container_name: innovationai_postgres
        hostname: innovationai_postgres
        image: postgres:13-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: app
            POSTGRES_USER: app
        volumes:
            - ./db:/var/lib/postgresql/data
