---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: three-tier-app
  name: three-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-app
  template:
    metadata:
      labels:
        app: three-tier-app
    spec:
      containers:
      - image: {account_id}.dkr.ecr.{region}.amazonaws.com/three-tier-app:latest
        name: three-tier-app
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"