---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: three-tier-app
  name: three-tier-app-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: three-tier-app
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: three-tier-app-svc-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
      app: three-tier-app